
import { Task, TaskStatus, SubTask } from '@/types/tasks';

// Helper to generate past/future dates
const getRelativeDate = (dayOffset: number): Date => {
  const date = new Date();
  date.setDate(date.getDate() + dayOffset);
  return date;
};

// Generate subtasks
const createSubtasks = (count: number): SubTask[] => {
  return Array.from({ length: count }, (_, i) => ({
    id: `subtask-${i + 1}`,
    title: `Subtask ${i + 1}`,
    completed: Math.random() > 0.5,
  }));
};

// Generate mock tasks
export const mockTasks: Task[] = [
  {
    id: 'task-001',
    title: 'Repair Workshop Ventilation',
    description: 'Fix the ventilation system in the main workshop to ensure proper air circulation.',
    assignedTo: ['user-001'],
    createdBy: 'user-admin',
    supervisor: 'user-manager',
    dueDate: getRelativeDate(2),
    startDate: getRelativeDate(-1),
    estimatedHours: 4,
    actualHours: 0,
    status: 'in_progress',
    priority: 'high',
    completion: 30,
    category: 'maintenance',
    tags: ['workshop', 'safety', 'ventilation'],
    isRecurring: false,
    subtasks: createSubtasks(3),
    relatedEquipment: ['equip-001'],
    attachments: [],
    comments: [
      {
        id: 'comment-001',
        taskId: 'task-001',
        userId: 'user-002',
        userName: 'Sarah Lopez',
        userAvatar: '',
        message: 'Ordered the replacement parts.',
        createdAt: getRelativeDate(-1)
      }
    ],
    timeEntries: [],
    createdAt: getRelativeDate(-3),
    updatedAt: getRelativeDate(-1),
  },
  {
    id: 'task-002',
    title: 'Monthly Safety Inspection',
    description: 'Conduct monthly safety inspection of all equipment in the barn.',
    assignedTo: ['user-002'],
    createdBy: 'user-admin',
    dueDate: getRelativeDate(0), // Today
    startDate: getRelativeDate(-2),
    estimatedHours: 2,
    actualHours: 1.5,
    status: 'in_progress',
    priority: 'medium',
    completion: 50,
    category: 'safety',
    tags: ['inspection', 'monthly', 'compliance'],
    isRecurring: true,
    subtasks: createSubtasks(5),
    relatedChecklists: ['checklist-001'],
    attachments: [
      {
        id: 'attach-001',
        name: 'Inspection_Checklist.pdf',
        url: '/documents/checklist.pdf',
        type: 'document',
        uploadedBy: 'user-admin',
        uploadedAt: getRelativeDate(-5)
      }
    ],
    comments: [],
    timeEntries: [
      {
        id: 'time-001',
        taskId: 'task-002',
        userId: 'user-002',
        startTime: getRelativeDate(-1),
        endTime: getRelativeDate(-1),
        duration: 90, // 1.5 hours in minutes
        description: 'Started equipment inspection',
        category: 'work'
      }
    ],
    createdAt: getRelativeDate(-7),
    updatedAt: getRelativeDate(-1),
  },
  {
    id: 'task-003',
    title: 'Order Safety Supplies',
    description: 'Restock PPE and first aid supplies for all barns and workshops.',
    assignedTo: ['user-001'],
    createdBy: 'user-admin',
    dueDate: getRelativeDate(-1), // Overdue
    startDate: getRelativeDate(-3),
    estimatedHours: 1,
    actualHours: 0,
    status: 'todo',
    priority: 'critical',
    completion: 0,
    category: 'inventory',
    tags: ['supplies', 'PPE', 'first-aid'],
    isRecurring: false,
    subtasks: createSubtasks(2),
    attachments: [],
    comments: [],
    timeEntries: [],
    createdAt: getRelativeDate(-5),
    updatedAt: getRelativeDate(-5),
  },
  {
    id: 'task-004',
    title: 'Tractor Service',
    description: 'Schedule regular maintenance service for the main tractor.',
    assignedTo: ['user-003'],
    createdBy: 'user-manager',
    dueDate: getRelativeDate(5),
    startDate: getRelativeDate(2),
    estimatedHours: 6,
    actualHours: 0,
    status: 'todo',
    priority: 'medium',
    completion: 0,
    category: 'maintenance',
    tags: ['tractor', 'scheduled', 'maintenance'],
    isRecurring: true,
    subtasks: createSubtasks(4),
    relatedEquipment: ['equip-002'],
    attachments: [],
    comments: [],
    timeEntries: [],
    createdAt: getRelativeDate(-2),
    updatedAt: getRelativeDate(-2),
  },
  {
    id: 'task-005',
    title: 'Update First Aid Stations',
    description: 'Restock and verify all first aid stations around the farm.',
    assignedTo: ['user-002'],
    createdBy: 'user-admin',
    dueDate: getRelativeDate(1),
    startDate: getRelativeDate(-1),
    estimatedHours: 3,
    actualHours: 2.5,
    status: 'review',
    priority: 'high',
    completion: 90,
    category: 'safety',
    tags: ['first-aid', 'compliance', 'safety'],
    isRecurring: true,
    subtasks: createSubtasks(6),
    attachments: [],
    comments: [],
    timeEntries: [],
    createdAt: getRelativeDate(-3),
    updatedAt: getRelativeDate(0),
  },
  {
    id: 'task-006',
    title: 'Inventory Count - Barn A',
    description: 'Complete monthly inventory count of all supplies in Barn A.',
    assignedTo: ['user-001', 'user-004'],
    createdBy: 'user-manager',
    dueDate: getRelativeDate(3),
    startDate: getRelativeDate(1),
    estimatedHours: 4,
    actualHours: 0,
    status: 'todo',
    priority: 'low',
    completion: 0,
    category: 'inventory',
    tags: ['inventory', 'monthly', 'barn-a'],
    isRecurring: true,
    subtasks: createSubtasks(3),
    attachments: [],
    comments: [],
    timeEntries: [],
    createdAt: getRelativeDate(-1),
    updatedAt: getRelativeDate(-1),
  },
  {
    id: 'task-007',
    title: 'Repair Gate B Latch',
    description: 'Fix broken latch on Gate B in the west pasture.',
    assignedTo: ['user-003'],
    createdBy: 'user-001',
    dueDate: getRelativeDate(1), // Tomorrow
    startDate: getRelativeDate(0),
    estimatedHours: 1,
    actualHours: 0,
    status: 'todo',
    priority: 'medium',
    completion: 0,
    category: 'maintenance',
    tags: ['gate', 'repair', 'pasture'],
    isRecurring: false,
    subtasks: createSubtasks(2),
    attachments: [],
    comments: [],
    timeEntries: [],
    createdAt: getRelativeDate(0),
    updatedAt: getRelativeDate(0),
  },
  {
    id: 'task-008',
    title: 'PPE Inspection - Workshop',
    description: 'Verify all personal protective equipment in the main workshop.',
    assignedTo: ['user-002'],
    createdBy: 'user-admin',
    dueDate: getRelativeDate(0), // Today
    startDate: getRelativeDate(-1),
    estimatedHours: 2,
    actualHours: 0,
    status: 'in_progress',
    priority: 'high',
    completion: 40,
    category: 'safety',
    tags: ['PPE', 'inspection', 'workshop', 'safety'],
    isRecurring: false,
    subtasks: createSubtasks(4),
    attachments: [],
    comments: [],
    timeEntries: [],
    createdAt: getRelativeDate(-2),
    updatedAt: getRelativeDate(-1),
  },
];
