// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// We need the default URL and KEY.
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? 'https://guorvjgmlnutohlzkfrk.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY ?? 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1b3J2amdtbG51dG9obHprZnJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MDM4MTcsImV4cCI6MjA2MjA3OTgxN30.gxSYeLX2rwbCgrsGJzLQtyDEN5o7uHOhN55X8nXV-2I';

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);